version: '3'

services:
  web:
    build: .
    image: speed-web:1.0
    container_name: web
    restart: always
    ports:
      - 8000:8888
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - backend
  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: always
  nginx:
    build: ./nginx
    image: speed-nginx:1.0
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - web

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: