"""empty message

Revision ID: c7945a648334
Revises: b6551782105a
Create Date: 2021-09-17 15:29:45.938506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7945a648334'
down_revision = 'b6551782105a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'total')
    # ### end Alembic commands ###
